/**
 * This file is autogenerated by Scaffold-HBAR (yarn foundry:deploy).
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    StrategyRegistry: {
      address: "0x0000000000000000000000000000000000000000",
      abi: [
        {
          type: "function",
          name: "anchorCheckpoint",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "sequenceNumber",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "runningHash",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "realizedPnl",
              type: "int128",
              internalType: "int128",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getStrategy",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct StrategyRegistry.Strategy",
              components: [
                {
                  name: "operator",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "topicNum",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "createdAt",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "paramsHash",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "venueAccount",
                  type: "string",
                  internalType: "string",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "latestCheckpoint",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct StrategyRegistry.Checkpoint",
              components: [
                {
                  name: "sequenceNumber",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "anchoredAt",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "realizedPnl",
                  type: "int128",
                  internalType: "int128",
                },
                {
                  name: "runningHash",
                  type: "bytes",
                  internalType: "bytes",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "listStrategies",
          inputs: [
            {
              name: "offset",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "limit",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "page",
              type: "tuple[]",
              internalType: "struct StrategyRegistry.Strategy[]",
              components: [
                {
                  name: "operator",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "topicNum",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "createdAt",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "paramsHash",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "venueAccount",
                  type: "string",
                  internalType: "string",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "register",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "topicNum",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "venueAccount",
              type: "string",
              internalType: "string",
            },
            {
              name: "paramsHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setActive",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "strategiesOf",
          inputs: [
            {
              name: "operator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "strategyCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOperator",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "newOperator",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "update",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "topicNum",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "paramsHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "CheckpointAnchored",
          inputs: [
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "sequenceNumber",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
            {
              name: "realizedPnl",
              type: "int128",
              indexed: false,
              internalType: "int128",
            },
            {
              name: "runningHash",
              type: "bytes",
              indexed: false,
              internalType: "bytes",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OperatorTransferred",
          inputs: [
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "previousOperator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOperator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StrategyRegistered",
          inputs: [
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "operator",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "topicNum",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StrategyStatusChanged",
          inputs: [
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "StrategyUpdated",
          inputs: [
            {
              name: "id",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "topicNum",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
            {
              name: "paramsHash",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "InvalidName",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidOperator",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidRunningHash",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidTopic",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOperator",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "StaleCheckpoint",
          inputs: [
            {
              name: "latest",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "proposed",
              type: "uint64",
              internalType: "uint64",
            },
          ],
        },
        {
          type: "error",
          name: "UnknownStrategy",
          inputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 0,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
